"""add_security_profiles_table

Revision ID: 3270212c6d7c
Revises: a2d799297537
Create Date: 2026-04-27 17:59:44.308406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3270212c6d7c'
down_revision: Union[str, None] = 'a2d799297537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_number', sa.String(length=64), nullable=True),
    sa.Column('shift', sa.Enum('morning', 'evening', 'night', 'rotating', name='security_shift', native_enum=False), server_default='rotating', nullable=False),
    sa.Column('assigned_building_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_profiles_assigned_building_id'), 'security_profiles', ['assigned_building_id'], unique=False)
    op.create_index(op.f('ix_security_profiles_badge_number'), 'security_profiles', ['badge_number'], unique=True)
    op.create_index(op.f('ix_security_profiles_user_id'), 'security_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_profiles_user_id'), table_name='security_profiles')
    op.drop_index(op.f('ix_security_profiles_badge_number'), table_name='security_profiles')
    op.drop_index(op.f('ix_security_profiles_assigned_building_id'), table_name='security_profiles')
    op.drop_table('security_profiles')
    # ### end Alembic commands ###
