"""add_building_id_to_announcements_and_events

Revision ID: 3c743e153ff6
Revises: 83d9dc687acb
Create Date: 2026-05-01 18:23:19.417996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c743e153ff6'
down_revision: Union[str, None] = '83d9dc687acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('building_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_announcements_building_id'), 'announcements', ['building_id'], unique=False)
    op.create_foreign_key('fk_announcements_building_id_buildings', 'announcements', 'buildings', ['building_id'], ['id'], ondelete='SET NULL')
    op.add_column('events', sa.Column('building_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_events_building_id'), 'events', ['building_id'], unique=False)
    op.create_foreign_key('fk_events_building_id_buildings', 'events', 'buildings', ['building_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_events_building_id_buildings', 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_building_id'), table_name='events')
    op.drop_column('events', 'building_id')
    op.drop_constraint('fk_announcements_building_id_buildings', 'announcements', type_='foreignkey')
    op.drop_index(op.f('ix_announcements_building_id'), table_name='announcements')
    op.drop_column('announcements', 'building_id')
    # ### end Alembic commands ###
