"""add_created_by_to_payments

Revision ID: 443ce5c7c242
Revises: d3612374dce5
Create Date: 2026-05-06 10:55:38.212035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443ce5c7c242'
down_revision: Union[str, None] = 'd3612374dce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payments_created_by'), 'payments', ['created_by'], unique=False)
    op.create_foreign_key(None, 'payments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_created_by'), table_name='payments')
    op.drop_column('payments', 'created_by')
    # ### end Alembic commands ###
