"""add_phase2_operations_tables

Revision ID: 6f0446b8b460
Revises: 8495e7d62ced
Create Date: 2026-04-27 17:40:47.469037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0446b8b460'
down_revision: Union[str, None] = '8495e7d62ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('maintenance_fee', 'parking', 'amenity', 'penalty', 'other', name='payment_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'overdue', 'waived', name='payment_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('transaction_ref', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_due_date'), 'payments', ['due_date'], unique=False)
    op.create_index(op.f('ix_payments_resident_id'), 'payments', ['resident_id'], unique=False)
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visitor_name', sa.String(length=150), nullable=False),
    sa.Column('visitor_phone', sa.String(length=30), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'checked_in', 'checked_out', 'denied', name='visitor_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_approved_by'), 'visitors', ['approved_by'], unique=False)
    op.create_index(op.f('ix_visitors_expected_date'), 'visitors', ['expected_date'], unique=False)
    op.create_index(op.f('ix_visitors_resident_id'), 'visitors', ['resident_id'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('plumbing', 'electrical', 'carpentry', 'cleaning', 'internet', 'other', name='maintenance_category', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='maintenance_priority', native_enum=False), server_default='medium', nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'cancelled', name='maintenance_status', native_enum=False), server_default='open', nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_resident_id'), 'maintenance_requests', ['resident_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_unit_id'), 'maintenance_requests', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_requests_unit_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_resident_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_visitors_resident_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_expected_date'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_approved_by'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_payments_resident_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_due_date'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
