"""add_security_tables

Revision ID: 7dcf3656996f
Revises: 3270212c6d7c
Create Date: 2026-04-28 11:28:11.542794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dcf3656996f'
down_revision: Union[str, None] = '3270212c6d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_points_building_id'), 'access_points', ['building_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('security', 'safety', 'maintenance', 'emergency', 'other', name='security_incident_category', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='security_incident_severity', native_enum=False), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved', 'closed', name='security_incident_status', native_enum=False), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_reported_by'), 'incidents', ['reported_by'], unique=False)
    op.create_table('patrol_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('checkpoints', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrol_routes_building_id'), 'patrol_routes', ['building_id'], unique=False)
    op.create_table('security_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_reports_created_at'), 'security_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_reports_created_by'), 'security_reports', ['created_by'], unique=False)
    op.create_table('access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('access_point_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('entry', 'exit', name='access_direction', native_enum=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_access_point_id'), 'access_logs', ['access_point_id'], unique=False)
    op.create_index(op.f('ix_access_logs_timestamp'), 'access_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_access_logs_user_id'), 'access_logs', ['user_id'], unique=False)
    op.create_table('patrol_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guard_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'cancelled', name='patrol_status', native_enum=False), server_default='in_progress', nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['patrol_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrol_rounds_guard_id'), 'patrol_rounds', ['guard_id'], unique=False)
    op.create_index(op.f('ix_patrol_rounds_route_id'), 'patrol_rounds', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patrol_rounds_route_id'), table_name='patrol_rounds')
    op.drop_index(op.f('ix_patrol_rounds_guard_id'), table_name='patrol_rounds')
    op.drop_table('patrol_rounds')
    op.drop_index(op.f('ix_access_logs_user_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_timestamp'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_access_point_id'), table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index(op.f('ix_security_reports_created_by'), table_name='security_reports')
    op.drop_index(op.f('ix_security_reports_created_at'), table_name='security_reports')
    op.drop_table('security_reports')
    op.drop_index(op.f('ix_patrol_routes_building_id'), table_name='patrol_routes')
    op.drop_table('patrol_routes')
    op.drop_index(op.f('ix_incidents_reported_by'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_access_points_building_id'), table_name='access_points')
    op.drop_table('access_points')
    # ### end Alembic commands ###
