"""add_resolution_note_and_updated_by_to_maintenance

Revision ID: d3612374dce5
Revises: f1e2d3c4b5a6
Create Date: 2026-05-05 12:46:23.465192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3612374dce5'
down_revision: Union[str, None] = 'f1e2d3c4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_requests', sa.Column('resolution_note', sa.Text(), nullable=True))
    op.add_column('maintenance_requests', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_maintenance_requests_updated_by'), 'maintenance_requests', ['updated_by'], unique=False)
    op.create_foreign_key(None, 'maintenance_requests', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_requests', type_='foreignkey')
    op.drop_index(op.f('ix_maintenance_requests_updated_by'), table_name='maintenance_requests')
    op.drop_column('maintenance_requests', 'updated_by')
    op.drop_column('maintenance_requests', 'resolution_note')
    # ### end Alembic commands ###
