"""add_shift_time_and_gate_to_security_profiles

Revision ID: e8461c6a7bb4
Revises: g1h2i3j4k5l6
Create Date: 2026-05-11 11:54:20.710261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8461c6a7bb4'
down_revision: Union[str, None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_profiles', sa.Column('shift_start_time', sa.String(length=5), nullable=True))
    op.add_column('security_profiles', sa.Column('shift_end_time', sa.String(length=5), nullable=True))
    op.add_column('security_profiles', sa.Column('assigned_gate', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_profiles', 'assigned_gate')
    op.drop_column('security_profiles', 'shift_end_time')
    op.drop_column('security_profiles', 'shift_start_time')
    # ### end Alembic commands ###
